version: '2'
networks:
  bigtangle-bridged-network:
    driver: bridge
services:
  mysql-bigtangle:
    image: docker-dev.art.intern/mysql:8.0.23
    container_name: mysql-bigtangle
    ports:
      - 3306:3306
    networks:
    - bigtangle-bridged-network
    environment: 
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: info
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
    
  bigtangle-server:
    build:
      context: bigtangle
    image: docker-dev.art.intern/j0904cui/bigtangle
    container_name: bigtangle-server
    ports:
    - 8086:8086
    depends_on:
    - mysql-bigtangle
    networks:
    - bigtangle-bridged-network
    environment:
      KAFKA_BOOTSTRAP_SERVERS:
      DB_HOSTNAME: mysql-bigtangle
      DB_PASSWORD: test1234
      SERVER_PORT: 8086
      DB_NAME: info
      SERVICE_MCMC: "true"
      SERVICE_MINING: "false"
      SERVER_MINERADDRESS: 1MxiDdUWQ5Aek872tJHpnGe7j75pwaGdZE 
      TOPIC_OUT_NAME: bigtangle
      CONSUMERIDSUFFIX:  
      REQUESTER: https://p.bigtangle.de:8088
      SERVER_NET: Mainnet
      

