server:
  port: ${SERVER_PORT:8089}
  ssl:
    enabled: ${SSL:false}
    key-store: ${KEYSTORE:src/main/resources/ca.pkcs12}
    key-store-password: ${KEYSTOREPW:changeit}
    keyStoreType: ${KEYSTORETYPE:PKCS12}


db:
  dbtype: ${DBTYPE:mysql}
  hostname: ${DB_HOSTNAME:localhost}
  port: ${DB_PORT:3306}
  dbName: ${DB_NAME:ordermatch}
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:test1234}

service:
  orderMatchService:
    rate: ${SERVICE_ORDERMATCH_RATE:10000}
    active: ${SERVICE_ORDERMATCH_ACTIVE:false}
    
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true