version: '2'
networks:
  bigtangle-bridged-network:
    driver: bridge
services:
  mysql-bigtangle:
    image: registry.dasimi.com/mysql
    container_name: mysql-bigtangle
    volumes:
        /data/mysql-bigtangle/var/lib/mysql:/var/lib/mysql
    networks:
    - bigtangle-bridged-network
    environment: 
      MYSQL_ROOT_PASSWORD: testpassword 
      MYSQL_DATABASE: info
    
  bigtangle-server:
    image: registry.dasimi.com/bigtangle-server
    container_name: bigtangle-server
    ports:
    - 8086:8086
    depends_on:
    - mysql-bigtangle
    networks:
    - bigtangle-bridged-network
    environment:
      KAFKA_BOOTSTRAP_SERVERS:
      DB_HOSTNAME: mysql-bigtangle
      DB_PASSWORD: testpassword
      SERVER_PORT: 8086
      DB_NAME: info
      SERVICE_MCMC: true
      SERVICE_MINING: false
      SERVER_MINERADDRESS: 1MxiDdUWQ5Aek872tJHpnGe7j75pwaGdZE 
      TOPIC_OUT_NAME: bigtangle
      CONSUMERIDSUFFIX:  
      REQUESTER: https://p.bigtangle.de:8088
      SERVER_NET: Mainnet
      

