version: '2'
networks:
  bignetcoin-bridged-network:
    driver: bridge
services:
  zookeeper-bignetcoin:
    image: wurstmeister/zookeeper
    container_name: zookeeper-bignetcoin
    restart: always
    ports:
    - 2181:2181
    networks:
    - bignetcoin-bridged-network

  kafka-bignetcoin:
    image: wurstmeister/kafka
    container_name: kafka-bignetcoin
    restart: always
    ports:
    - 9092:9092
    networks:
    - bignetcoin-bridged-network
    environment:
      ADVERTISED_HOST: kafka-bignetcoin
      ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-bignetcoin:2181
      KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
  mysql-bignetcoin:
    image: registry.dasimi.com/mysql
    container_name: mysql-bignetcoin
    ports:
    - 3306:3306
    networks:
    - bignetcoin-bridged-network
  bignetcoin-server:
    image: registry.dasimi.com/com.bignetcoin/bignetcoin.bignetcoin-server
    container_name: bignetcoin-server
    ports:
    - 8080:8080
    depends_on:
    - kafka-bignetcoin
    - mysql-bignetcoin
    networks:
    - bignetcoin-bridged-network
    environment:
      KAFKA_BROKER: kafka-bignetcoin:9092
      KAFKA_BOOTSTRAP_SERVERS: kafka-bignetcoin:9092
      KAFKA_ZOO_KEEPER_SERVER: kafka-bignetcoin:2181
      KAFKA_SCHEMA_REGISTRY_URL: http://kafka-bignetcoin:8081
      CASSANDRA_NODES: mysql-bignetcoin
