version: '2'
networks:
  bigtangle-bridged-network:
    driver: bridge
services:
  mysql-bigtangle:
    image: bigtangle/mysql
    container_name: mysql-bigtangle
    volumen:
        /data/var/lib/mysql:/var/lib/mysql
    ports:
    - 3306:3306
    networks:
    - bigtangle-bridged-network
    environment: 
      MYSQL_ROOT_PASSWORD: testpassword 
      MYSQL_DATABASE: info
    
  bigtangle-server:
    image: bigtangle/bigtangle-server
    container_name: bigtangle-server
    ports:
    - 8080:8080
    depends_on:
    - mysql-bigtangle
    networks:
    - bigtangle-bridged-network
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka.bigtangle.org:9092
      DB_HOSTNAME: mysql-bigtangle
      DB_PASSWORD: testpassword
      SERVER_PORT: 8088
      DB_NAME: info
      SERVICE_MILESTONE_ACTIVE: true
      SERVER_MINERADDRESS: 1MxiDdUWQ5Aek872tJHpnGe7j75pwaGdZE
      BOOT_STRAP_SERVERS: $KAFKA    
      TOPIC_OUT_NAME: bigtangle
      CONSUMERIDSUFFIX:  yourid.bigtangle-server
      REQUESTER: https://p.bigtangle.org:8088, https://p.bigtangle.de:8088
      SERVER_NET: Mainnet
      

