version: '2'
networks:
  bigtangle-bridged-network:
    driver: bridge
services:
  zookeeper-bigtangle:
    image: wurstmeister/zookeeper
    container_name: zookeeper-bigtangle
    ports:
    - 2181:2181
    networks:
    - bigtangle-bridged-network

  kafka-bigtangle:
    image: wurstmeister/kafka
    container_name: kafka-bigtangle
    ports:
    - 9092:9092
    networks:
    - bigtangle-bridged-network
    environment:
      ADVERTISED_HOST: kafka-bigtangle
      ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-bigtangle:2181
      KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
  mysql-bigtangle:
    image: registry.dasimi.com/mysql
    container_name: mysql-bigtangle
    ports:
    - 3306:3306
    networks:
    - bigtangle-bridged-network
  bigtangle-server:
    image: registry.dasimi.com/com.bigtangle/bigtangle.bigtangle-server
    container_name: bigtangle-server
    ports:
    - 8080:8080
    depends_on:
    - kafka-bigtangle
    - mysql-bigtangle
    networks:
    - bigtangle-bridged-network
    environment:
      KAFKA_BROKER: kafka-bigtangle:9092
      KAFKA_BOOTSTRAP_SERVERS: kafka-bigtangle:9092
      KAFKA_ZOO_KEEPER_SERVER: kafka-bigtangle:2181
      KAFKA_SCHEMA_REGISTRY_URL: http://kafka-bigtangle:8081
      DB_HOSTNAME: mysql-bigtangle
