server:
  port: ${SERVER_PORT:8089}
  ssl:
    enabled: ${SSL:true}
    key-store: ${KEYSTORE:src/main/resources/ca.pkcs12}
    key-store-password: ${KEYSTOREPW:changeit}
    keyStoreType: ${KEYSTORETYPE:PKCS12}

bigtangleweb:
  bigtangle: ${BIGTANGLEURL:https://p.bigtangle.org:18088/}
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true