server:
  port: ${SERVER_PORT:8089}
  ssl:
    enabled: ${SSL:false}
    key-store: ${KEYSTORE:src/main/resources/ca.pkcs12}
    key-store-password: ${KEYSTOREPW:changeit}
    keyStoreType: ${KEYSTORETYPE:PKCS12}
    
  serverURL: ${SERVERURL:https://bigtangle.org/}
  reset: ${RESET:false}

spring:
    mvc:
        view:
            suffix: .jsp
            prefix: /WEB-INF/jsp/
    thymeleaf:
        cache: false
        enabled: false

db:
  dbtype: ${DBTYPE:mysql}
  hostname: ${DB_HOSTNAME:localhost}
  port: ${DB_PORT:3306}
  dbName: ${DB_NAME:info}
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:test1234}

service:
  giveMoneyService:
    rate: ${SERVICE_GIVEMONEY_RATE:5000}
    active: ${SERVICE_GIVEMONEY_ACTIVE:true}
    
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true