/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bigtangle_equihash_EquihashSolver */

#ifndef _Included_net_bigtangle_equihash_EquihashSolver
#define _Included_net_bigtangle_equihash_EquihashSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bigtangle_equihash_EquihashSolver
 * Method:    runProofSolver
 * Signature: (III)Lnet/bigtangle/equihash/EquihashProof;
 */
JNIEXPORT jobject JNICALL Java_net_bigtangle_equihash_EquihashSolver_runProofSolver
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
