server:
  neighbors: 
  port: ${SERVER_PORT:8088}
  udp_receiver_port: 
  tcp_receiver_port: 
  debug: ${SERVER_DEBUG:true}
  testnet: ${SERVER_TESTNET:true}
  remote: ${SERVER_REMOTE:0.0.0.0}
  remote_auth: 
  remote_limit_api: ${SERVER_REMOTE_LIMIT_API:5000}
  mineraddress:  ${SERVER_MINERADDRESS:030d8952f6c079f60cd26eb3ba83cf16a81c51fc8e47b767721fa38b5e20092a75}

db:
  dbtype: ${DBTYPE:phoenix}
  hostname: ${DB_HOSTNAME:cn.phoenix.bigtangle.net}
  port: ${DB_PORT:8765}
  dbName: ${DB_NAME:}
  username: ${DB_USERNAME:}
  password: ${DB_PASSWORD:}

service:
  milestoneschedule:
    rate: ${SERVICE_MILESTONE_RATE:500000}
    retention-time-in-minutes: ${service_HOUSEKEEPING_RETENTION:1440} # 24*60 == 1 Tag
    active: ${SERVICE_MILESTONE_ACTIVE:true}
    
kafka:
  broker: ${KAFKA_BROKER:cn.kafka.bigtangle.net:9092}
  bootstrapServers: ${BOOT_STRAP_SERVERS:cn.kafka.bigtangle.net:9092}
  zooKeeperServer: ${ZOOKEEPER_SERVERS:cn.zookeeper.bigtangle.net:2281}
  topicOutName: ${TOPIC_OUT_NAME:bigtangle}

    
---
spring:
  profiles: ${SPRING_PROFILES:testnet}