server:
  neighbors: 
  port: 14265
  udp_receiver_port: 
  tcp_receiver_port: 
  debug: true
  testnet: true
  remote: 0.0.0.0
  remote_auth: 
  remote_limit_api: 5000

cassandra:
  keyspace: dk_fahrtwissen
  nodes: cassandra-as-vdv-aus
