server:
  port: ${SERVER_PORT:8088}
  net: ${SERVER_NET:Mainnet}
  requester: ${REQUESTER:}
  mineraddress: ${SERVER_MINERADDRESS:mjWvzPZz4YJtWqb7ux7cdgq5G7rzkg3bXG}
  serverversion: ${SERVERVERSION:0.3.3}
  clientversion: ${CLIENTVERSION:0.3.3}
  ssl:
    enabled: ${SSL:false}
    key-store: ${KEYSTORE:src/main/resources/ca.pkcs12}
    key-store-password: ${KEYSTOREPW:changeit}
    keyStoreType: ${KEYSTORETYPE:PKCS12}

db:
  dbtype: ${DBTYPE:mysql}
  hostname: ${DB_HOSTNAME:localhost}
  port: ${DB_PORT:3306}
  dbName: ${DB_NAME:info}
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:test1234}


service:
  milestoneschedule:
    rate: ${SERVICE_MILESTONE_RATE:15000}
    active: ${SERVICE_MILESTONE_ACTIVE:false}
    
kafka:
  bootstrapServers: ${BOOT_STRAP_SERVERS:}
  topicOutName: ${TOPIC_OUT_NAME:bigtangle}
  consumerIdSuffix: ${CONSUMERIDSUFFIX:bigtangletest}
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true